---
# requirements.yml
# Ansible Collections Requirements
# Install with: ansible-galaxy collection install -r requirements.yml

collections:
  # Required for syslog logging
  - name: community.general
    version: ">=6.0.0"

  # Optional: For MySQL database backups in pre_backup_tasks
  # Uncomment if you use MySQL dumps
  # - name: community.mysql
  #   version: ">=3.0.0"

  # Optional: For PostgreSQL database backups in pre_backup_tasks
  # Uncomment if you use PostgreSQL dumps
  # - name: community.postgresql
  #   version: ">=2.0.0"

  # Optional: For Docker container management in pre/post_backup_tasks
  # Uncomment if you manage Docker containers
  # - name: community.docker
  #   version: ">=3.0.0"