---
# requirements.yml
# Ansible Collections Requirements
# Install with: ansible-galaxy collection install -r Requirements.yml

collections:
  # Required: Basic Ansible modules
  - name: community.general
    version: ">=6.0.0"

  # Optional: For MySQL database management in hooks
  # Uncomment if you use MySQL in your backup hooks
  # - name: community.mysql
  #   version: ">=3.0.0"

  # Optional: For PostgreSQL database management in hooks
  # Uncomment if you use PostgreSQL in your backup hooks
  # - name: community.postgresql
  #   version: ">=2.0.0"

  # Optional: For Docker container management in hooks
  # Uncomment if you manage Docker containers in your hooks
  # - name: community.docker
  #   version: ">=3.0.0"