---
# group_vars/all/vars.yml
# Example Configuration for Restic Backup Role (Systemd-Based)

# ========================================
# BACKEND CONFIGURATION
# ========================================

restic_backend_type: "s3"  # s3, local, sftp

# S3 Backend
restic_s3_bucket: "my-company-backups"
restic_s3_region: "eu-central-1"
restic_s3_endpoint: ""  # Empty for AWS, or "https://minio.example.com" for MinIO
restic_s3_prefix: "restic"

# Credentials from vault
restic_s3_access_key: "{{ vault_aws_access_key }}"
restic_s3_secret_key: "{{ vault_aws_secret_key }}"

# Local Backend (Alternative)
# restic_backend_type: "local"
# restic_local_path: "/mnt/backup/restic"

# ========================================
# ENCRYPTION KEYS (2-Key System)
# ========================================

# Generic key - used as fallback or for shared repositories
restic_generic_password: "{{ vault_restic_generic_password }}"

# Playbook-specific key - used for this specific playbook/environment
restic_playbook_password: "{{ vault_restic_playbook_password }}"

# Use playbook-specific key by default
restic_use_playbook_key: true

# ========================================
# BACKUP SOURCES
# ========================================

restic_backup_sources:
  - name: "var-www"
    path: "/var/www"
    tags: ["web", "production"]
    enabled: true

  - name: "etc"
    path: "/etc"
    tags: ["config", "system"]
    enabled: true

  - name: "var-backups"
    path: "/var/backups"
    tags: ["dumps", "database"]
    enabled: true
    # Example: Database backup with hooks
    # pre_backup_commands:
    #   - "mysqldump --all-databases > /var/backups/mysql-all.sql"
    # post_backup_commands:
    #   - "rm -f /var/backups/mysql-all.sql"

  # - name: "home"
  #   path: "/home"
  #   tags: ["userdata"]
  #   enabled: false

# ========================================
# EXCLUSIONS
# ========================================

restic_backup_excludes:
  - "*.tmp"
  - "*.cache"
  - "*.log"
  - "*/cache/*"
  - "*/tmp/*"
  - "*/node_modules/*"
  - "*/vendor/*"
  - "*/.git/*"
  - "*/lost+found/*"
  - "*.pyc"
  - "__pycache__"

# ========================================
# BACKUP BEHAVIOR
# ========================================

restic_force_rescan: false
restic_force_rescan_day: 0  # 0=disabled, 1-31=day of month

# ========================================
# SYSTEMD TIMER CONFIGURATION
# ========================================

# Backup timer (runs daily at 2am +/- 30min randomization)
restic_timer_on_calendar: "02:00"
restic_timer_randomized_delay: "30min"

# Prune timer (runs weekly)
restic_prune_timer_on_calendar: "weekly"

# Check timer (runs weekly)
restic_check_timer_on_calendar: "weekly"

# Scan timer (runs daily)
restic_scan_timer_on_calendar: "daily"

# ========================================
# RETENTION POLICY
# ========================================

restic_retention_keep_last: 7
restic_retention_keep_hourly: 24
restic_retention_keep_daily: 14
restic_retention_keep_weekly: 8
restic_retention_keep_monthly: 12
restic_retention_keep_yearly: 5

# ========================================
# LOCK FILE MANAGEMENT
# ========================================

# Maximum age of lock file in hours before it's considered stale
restic_lock_max_age_hours: 12

# ========================================
# MONITORING
# ========================================

restic_enable_checkmk: true
restic_enable_syslog: true

# ========================================
# PERFORMANCE TUNING
# ========================================

restic_read_concurrency: 2
restic_upload_limit_kbps: 0      # 0 = unlimited, 1024 = 1 MiB/s
restic_download_limit_kbps: 0    # 0 = unlimited

# CPU and I/O limits for systemd units
restic_cpu_quota: 80
restic_io_weight: 100
restic_nice_level: 10

# ========================================
# DEBUG MODE
# ========================================

restic_debug_mode: false  # WARNING: Only for testing!
