---
# group_vars/all/vars.yml
# Example Configuration for Restic Backup Role (Systemd-Based)

# ========================================
# BACKEND CONFIGURATION
# ========================================

restic_backend_type: "s3"  # s3, local, sftp

# S3 Backend
restic_s3_bucket: "my-company-backups"
restic_s3_region: "eu-central-1"
restic_s3_endpoint: ""  # Empty for AWS, or "https://minio.example.com" for MinIO
restic_s3_prefix: "restic"

# Credentials from vault
restic_s3_access_key: "{{ vault_s3_access_key }}"
restic_s3_secret_key: "{{ vault_s3_secret_key }}"

# Local Backend (Alternative)
# restic_backend_type: "local"
# restic_local_path: "/mnt/backup/restic"

# ========================================
# ENCRYPTION
# ========================================

# Repository password from vault
# CRITICAL: Without this password, ALL backups are LOST!
restic_password: "{{ vault_restic_password }}"

# ========================================
# BACKUP SOURCES
# ========================================

restic_backup_sources:
  - name: "var-www"
    path: "/var/www"
    tags: ["web", "production"]
    enabled: true

  - name: "etc"
    path: "/etc"
    tags: ["config", "system"]
    enabled: true

  - name: "var-backups"
    path: "/var/backups"
    tags: ["dumps", "database"]
    enabled: true
    # Example: Database backup with hooks (see hooks/pre-backup-example.sh)
    # hook_pre_script: "{{ playbook_dir }}/hooks/pre-backup-var-backups.sh"
    # hook_post_script: "{{ playbook_dir }}/hooks/post-backup-var-backups.sh"

  # - name: "home"
  #   path: "/home"
  #   tags: ["userdata"]
  #   enabled: false

# ========================================
# EXCLUSIONS
# ========================================

restic_backup_excludes:
  - "*.tmp"
  - "*.cache"
  - "*.log"
  - "*/cache/*"
  - "*/tmp/*"
  - "*/node_modules/*"
  - "*/vendor/*"
  - "*/.git/*"
  - "*/lost+found/*"
  - "*.pyc"
  - "__pycache__"

# ========================================
# BACKUP BEHAVIOR
# ========================================

restic_force_rescan: false
restic_force_rescan_day: 0  # 0=disabled, 1-31=day of month

# ========================================
# SYSTEMD TIMER CONFIGURATION
# ========================================

# Backup timer (runs daily at 2am +/- 30min randomization)
restic_timer_on_calendar: "02:00"
restic_timer_randomized_delay: "30min"

# Prune timer (runs weekly)
restic_prune_timer_on_calendar: "weekly"

# Check timer (runs weekly)
restic_check_timer_on_calendar: "weekly"

# Scan timer (runs daily)
restic_scan_timer_on_calendar: "daily"

# ========================================
# RETENTION POLICY
# ========================================

restic_retention_keep_last: 7
restic_retention_keep_hourly: 24
restic_retention_keep_daily: 14
restic_retention_keep_weekly: 8
restic_retention_keep_monthly: 12
restic_retention_keep_yearly: 5

# ========================================
# RESTIC LOCK MANAGEMENT
# ========================================

# Stale locks are automatically removed before operations
# Restic's 'restic unlock' removes locks older than 30 minutes

# Systemd restart configuration (long-term retry on failure)
# Services automatically retry when failing due to locked repository
restic_restart_sec: "15min"           # Wait between retry attempts
restic_restart_max_attempts: 0        # 0 = unlimited retries until success

# Backup timeout (0 = unlimited, recommended for large backups)
restic_backup_timeout_seconds: 0      # Per-source override: timeout_seconds

# Repository integrity check configuration
restic_check_read_data: false         # Full data verification (slow)
restic_check_read_data_subset: ""     # Partial check: "1/12", "10%", or "50M"

# ========================================
# MONITORING
# ========================================

restic_enable_checkmk: true
restic_enable_syslog: true

# ========================================
# PERFORMANCE TUNING
# ========================================

restic_read_concurrency: 2
restic_upload_limit_kbps: 0      # 0 = unlimited, 1024 = 1 MiB/s
restic_download_limit_kbps: 0    # 0 = unlimited

# CPU and I/O limits for systemd units
restic_cpu_quota: 80
restic_io_weight: 100
restic_nice_level: 10

# ========================================
# DEBUG MODE
# ========================================

restic_debug_mode: false  # WARNING: Only for testing!
