---
# roles/restic/tasks/directories.yml
# Create required directories for Restic

- name: Create Restic configuration directory
  ansible.builtin.file:
    path: "{{ restic_config_dir }}"
    state: directory
    mode: '0700'
    owner: root
    group: root

- name: Create Restic password directory
  ansible.builtin.file:
    path: "{{ restic_config_dir }}/passwords"
    state: directory
    mode: '0700'
    owner: root
    group: root

- name: Create Restic scripts directory
  ansible.builtin.file:
    path: "{{ restic_scripts_dir }}"
    state: directory
    mode: '0755'
    owner: root
    group: root

- name: Create Restic hooks directory
  ansible.builtin.file:
    path: "{{ restic_hooks_dir }}"
    state: directory
    mode: '0755'
    owner: root
    group: root

- name: Ensure Check_MK spool directory exists
  ansible.builtin.file:
    path: "{{ restic_checkmk_spool_dir }}"
    state: directory
    mode: '0755'
  when: restic_enable_checkmk | bool

- name: Create exclude file
  ansible.builtin.copy:
    dest: "{{ restic_config_dir }}/excludes.txt"
    mode: '0644'
    content: "{{ restic_backup_excludes | join('\n') }}\n"
