---
# roles/restic/tasks/encryption.yml
# Deploy repository encryption password

- name: Deploy repository password file
  ansible.builtin.copy:
    dest: "{{ restic_config_dir }}/passwords/{{ restic_password_file }}"
    content: "{{ restic_password }}"
    mode: '0600'
    owner: root
    group: root
  no_log: "{{ not restic_debug_mode }}"
  when: restic_password | length > 0
