---
# roles/restic/tasks/install.yml
# Install Restic package on target systems

- name: Enable EPEL repository (RHEL/Rocky/Alma)
  ansible.builtin.dnf:
    name: epel-release
    state: present
  when: ansible_os_family == "RedHat"

- name: Install Restic (RHEL/Rocky/Alma)
  ansible.builtin.dnf:
    name: "{{ restic_package_name }}"
    state: present
  when: ansible_os_family == "RedHat"

- name: Install Restic (Debian/Ubuntu)
  ansible.builtin.apt:
    name: "{{ restic_package_name }}"
    state: present
    update_cache: yes
  when: ansible_os_family == "Debian"

- name: Install additional packages
  ansible.builtin.package:
    name: "{{ restic_additional_packages }}"
    state: present
