---
# roles/restic/tasks/main.yml
# Restic Backup Role - Main Tasks (Systemd-Based)
#
# This role deploys Restic backup solution with systemd integration
# - Systemd service units per backup source and job type
# - Native Restic hook system for pre/post backup tasks
# - Secure encryption with password file
# - CheckMK monitoring integration
# - Lock management with stale lock detection and automatic retry

# ========================================
# VALIDATION
# ========================================

- name: Validate configuration
  ansible.builtin.include_tasks: validate.yml
  tags:
    - restic
    - validate
    - always

# ========================================
# INSTALLATION
# ========================================

- name: Install Restic package
  ansible.builtin.include_tasks: install.yml
  tags:
    - restic
    - install

# ========================================
# SETUP (Directories & Encryption)
# ========================================

- name: Setup directories and encryption
  ansible.builtin.include_tasks: setup.yml
  tags:
    - restic
    - setup
    - config
    - encryption

# ========================================
# BACKEND CONFIGURATION
# ========================================

- name: Configure backup backend
  ansible.builtin.include_tasks: backend.yml
  tags:
    - restic
    - backend

# ========================================
# REPOSITORY INITIALIZATION
# ========================================

- name: Initialize Restic repository
  ansible.builtin.include_tasks: repository.yml
  tags:
    - restic
    - repository

# ========================================
# SCRIPTS AND HOOKS
# ========================================

- name: Deploy scripts and hooks
  ansible.builtin.include_tasks: scripts_and_hooks.yml
  tags:
    - restic
    - scripts
    - hooks

# ========================================
# SYSTEMD UNITS AND TIMERS
# ========================================

- name: Deploy and manage systemd units
  ansible.builtin.include_tasks: systemd_units.yml
  tags:
    - restic
    - systemd
    - timers
