---
# roles/restic/tasks/main.yml
# Restic Backup Role - Main Tasks (Systemd-Based)
#
# This role deploys Restic backup solution with systemd integration
# - Systemd service units per backup source and job type
# - Native Restic hook system for pre/post backup tasks
# - 2-key encryption system (generic + playbook-specific)
# - CheckMK monitoring integration
# - Lock management with stale lock detection

# ========================================
# INSTALLATION
# ========================================

- name: Install Restic package
  ansible.builtin.include_tasks: install.yml
  tags:
    - restic
    - install

# ========================================
# DIRECTORIES & CONFIGURATION
# ========================================

- name: Create directories and configuration files
  ansible.builtin.include_tasks: directories.yml
  tags:
    - restic
    - config

# ========================================
# ENCRYPTION KEYS (2-Key System)
# ========================================

- name: Deploy encryption keys
  ansible.builtin.include_tasks: encryption.yml
  tags:
    - restic
    - encryption

# ========================================
# BACKEND CONFIGURATION
# ========================================

- name: Configure backup backend
  ansible.builtin.include_tasks: backend.yml
  tags:
    - restic
    - backend

# ========================================
# REPOSITORY INITIALIZATION
# ========================================

- name: Initialize Restic repository
  ansible.builtin.include_tasks: repository.yml
  tags:
    - restic
    - repository

# ========================================
# DEPLOY SCRIPTS
# ========================================

- name: Deploy backup and monitoring scripts
  ansible.builtin.include_tasks: scripts.yml
  tags:
    - restic
    - scripts

# ========================================
# DEPLOY HOOKS
# ========================================

- name: Deploy pre/post backup hooks
  ansible.builtin.include_tasks: hooks.yml
  tags:
    - restic
    - hooks

# ========================================
# DEPLOY SYSTEMD UNITS
# ========================================

- name: Deploy systemd service and timer units
  ansible.builtin.include_tasks: systemd.yml
  tags:
    - restic
    - systemd

# ========================================
# ENABLE AND START TIMERS
# ========================================

- name: Enable and start systemd timers
  ansible.builtin.include_tasks: timers.yml
  tags:
    - restic
    - timers
