---
# roles/restic/tasks/repository.yml
# Initialize Restic repository

- name: Set base environment for repository operations
  ansible.builtin.set_fact:
    restic_env:
      RESTIC_REPOSITORY: "{{ restic_repository }}"
      RESTIC_PASSWORD_FILE: "{{ restic_config_dir }}/passwords/{{ restic_password_file }}"
  no_log: "{{ not restic_debug_mode }}"
  tags:
    - restic
    - repository

- name: Add S3 credentials to environment
  ansible.builtin.set_fact:
    restic_env: "{{ restic_env | combine({
      'AWS_ACCESS_KEY_ID': restic_s3_access_key,
      'AWS_SECRET_ACCESS_KEY': restic_s3_secret_key,
      'AWS_DEFAULT_REGION': restic_s3_region
    }) }}"
  when: restic_backend_type == "s3"
  no_log: "{{ not restic_debug_mode }}"
  tags:
    - restic
    - repository

- name: Check if repository exists
  ansible.builtin.shell:
    cmd: restic snapshots
  environment: "{{ restic_env }}"
  register: restic_repo_check
  failed_when: false
  changed_when: false
  no_log: "{{ not restic_debug_mode }}"
  tags:
    - restic
    - repository

- name: Initialize repository if not exists
  ansible.builtin.command:
    cmd: restic init
  environment: "{{ restic_env }}"
  when: restic_repo_check.rc != 0
  register: restic_repo_init
  failed_when:
    - restic_repo_init.rc != 0
    - "'already initialized' not in restic_repo_init.stderr"
    - "'already initialized' not in restic_repo_init.stdout"
  changed_when: "'created restic repository' in restic_repo_init.stdout or 'created restic repository' in restic_repo_init.stderr"
  no_log: "{{ not restic_debug_mode }}"
  tags:
    - restic
    - repository

- name: Verify repository was initialized successfully
  ansible.builtin.shell:
    cmd: restic snapshots
  environment: "{{ restic_env }}"
  register: restic_repo_verify
  when: restic_repo_init is changed
  failed_when: restic_repo_verify.rc != 0
  changed_when: false
  no_log: "{{ not restic_debug_mode }}"
  tags:
    - restic
    - repository

- name: Confirm repository status
  ansible.builtin.debug:
    msg: "Repository {{ restic_repository }} is ready"
  when: restic_repo_check.rc == 0 or (restic_repo_init is defined and restic_repo_init is changed)
  tags:
    - restic
    - repository
