---
# roles/restic/tasks/scripts_and_hooks.yml
# Deploy backup scripts, helper scripts, and pre/post backup hooks

# ========================================
# BACKUP AND MONITORING SCRIPTS
# ========================================

- name: Deploy CheckMK status script
  ansible.builtin.template:
    src: scripts/restic-checkmk-status.sh.j2
    dest: "{{ restic_scripts_dir }}/restic-checkmk-status.sh"
    mode: '0755'
    owner: root
    group: root
  when: restic_enable_checkmk | default(true) | bool
  tags:
    - restic
    - scripts

- name: Deploy backup scripts for each source
  ansible.builtin.template:
    src: "scripts/restic-backup.sh.j2"
    dest: "{{ restic_scripts_dir }}/restic-backup-{{ item.name }}.sh"
    mode: '0755'
    owner: root
    group: root
  loop: "{{ restic_backup_sources | selectattr('enabled') | list }}"
  loop_control:
    label: "backup-{{ item.name }}"
  when: restic_enable_backup | bool
  tags:
    - restic
    - scripts

- name: Deploy scan scripts for each source
  ansible.builtin.template:
    src: "scripts/restic-scan.sh.j2"
    dest: "{{ restic_scripts_dir }}/restic-scan-{{ item.name }}.sh"
    mode: '0755'
    owner: root
    group: root
  loop: "{{ restic_backup_sources | selectattr('enabled') | list }}"
  loop_control:
    label: "scan-{{ item.name }}"
  when: restic_enable_scan | bool
  tags:
    - restic
    - scripts

# ========================================
# HELPER SCRIPTS
# ========================================

- name: Create helper scripts directory
  ansible.builtin.file:
    path: "{{ restic_helpers_dir }}"
    state: directory
    mode: '0755'
    owner: root
    group: root
  tags:
    - restic
    - scripts

- name: Deploy helper scripts
  ansible.builtin.template:
    src: "scripts/{{ item }}.sh.j2"
    dest: "{{ restic_helpers_dir }}/{{ item }}.sh"
    mode: '0755'
    owner: root
    group: root
  loop:
    - restic-restore
    - restic-repo-info
  loop_control:
    label: "{{ item }}"
  tags:
    - restic
    - scripts

# ========================================
# PRE/POST BACKUP HOOKS
# ========================================
#
# Hooks use Restic's native hook system (RESTIC_PRE_SCRIPT, RESTIC_POST_SCRIPT)
#
# Option 1: Global hooks directory (restic_custom_hooks_dir)
#   - Copies hooks from control node: pre-backup-<source>.sh, post-backup-<source>.sh
#
# Option 2: Per-source hook scripts (item.hook_pre_script, item.hook_post_script)
#   - Copies specific hook script per source
#
# Option 3: Manual hook management
#   - User manually creates hooks on target hosts in restic_hooks_dir
#
# Note: Hooks are optional. If not present, backup runs without hooks.

- name: Copy pre-backup hooks from custom directory
  ansible.builtin.copy:
    src: "{{ restic_custom_hooks_dir }}/pre-backup-{{ item.name }}.sh"
    dest: "{{ item.hook_script_dir | default(restic_hooks_dir) }}/pre-backup-{{ item.name }}.sh"
    mode: '0755'
    owner: root
    group: root
  loop: "{{ restic_backup_sources | selectattr('enabled') | list }}"
  loop_control:
    label: "pre-{{ item.name }}"
  when:
    - restic_custom_hooks_dir | length > 0
    - item.hook_pre_script is not defined
  ignore_errors: yes  # Hook might not exist for this source
  tags:
    - restic
    - hooks

- name: Copy post-backup hooks from custom directory
  ansible.builtin.copy:
    src: "{{ restic_custom_hooks_dir }}/post-backup-{{ item.name }}.sh"
    dest: "{{ item.hook_script_dir | default(restic_hooks_dir) }}/post-backup-{{ item.name }}.sh"
    mode: '0755'
    owner: root
    group: root
  loop: "{{ restic_backup_sources | selectattr('enabled') | list }}"
  loop_control:
    label: "post-{{ item.name }}"
  when:
    - restic_custom_hooks_dir | length > 0
    - item.hook_post_script is not defined
  ignore_errors: yes  # Hook might not exist for this source
  tags:
    - restic
    - hooks

- name: Copy pre-backup per-source hook scripts
  ansible.builtin.copy:
    src: "{{ item.hook_pre_script }}"
    dest: "{{ item.hook_script_dir | default(restic_hooks_dir) }}/pre-backup-{{ item.name }}.sh"
    mode: '0755'
    owner: root
    group: root
  loop: "{{ restic_backup_sources | selectattr('enabled') | list }}"
  loop_control:
    label: "pre-{{ item.name }}"
  when:
    - item.hook_pre_script is defined
    - item.hook_pre_script | length > 0
  tags:
    - restic
    - hooks

- name: Copy post-backup per-source hook scripts
  ansible.builtin.copy:
    src: "{{ item.hook_post_script }}"
    dest: "{{ item.hook_script_dir | default(restic_hooks_dir) }}/post-backup-{{ item.name }}.sh"
    mode: '0755'
    owner: root
    group: root
  loop: "{{ restic_backup_sources | selectattr('enabled') | list }}"
  loop_control:
    label: "post-{{ item.name }}"
  when:
    - item.hook_post_script is defined
    - item.hook_post_script | length > 0
  tags:
    - restic
    - hooks
