---
# roles/restic/tasks/scripts.yml
# Deploy backup and monitoring scripts

- name: Deploy CheckMK status script
  ansible.builtin.template:
    src: scripts/checkmk-status.sh.j2
    dest: "{{ restic_scripts_dir }}/checkmk-status.sh"
    mode: '0755'
    owner: root
    group: root

- name: Deploy backup scripts for each source
  ansible.builtin.template:
    src: scripts/backup.sh.j2
    dest: "{{ restic_scripts_dir }}/backup-{{ item.name }}.sh"
    mode: '0755'
    owner: root
    group: root
  loop: "{{ restic_backup_sources | selectattr('enabled') | list }}"
  loop_control:
    label: "{{ item.name }}"

- name: Deploy scan scripts for each source
  ansible.builtin.template:
    src: scripts/scan.sh.j2
    dest: "{{ restic_scripts_dir }}/scan-{{ item.name }}.sh"
    mode: '0755'
    owner: root
    group: root
  loop: "{{ restic_backup_sources | selectattr('enabled') | list }}"
  loop_control:
    label: "{{ item.name }}"
