---
# roles/restic/tasks/timers.yml
# Enable and start systemd timers

- name: Flush handlers to reload systemd
  ansible.builtin.meta: flush_handlers

- name: Enable and start backup timers
  ansible.builtin.systemd:
    name: "restic-backup@{{ item.name }}.timer"
    enabled: yes
    state: started
    daemon_reload: yes
  loop: "{{ restic_backup_sources | selectattr('enabled') | list }}"
  loop_control:
    label: "{{ item.name }}"
  when: restic_enable_backup | bool and restic_enable_timers | bool

- name: Enable and start prune timer for first source
  ansible.builtin.systemd:
    name: "restic-prune@{{ (restic_backup_sources | selectattr('enabled') | list | first).name }}.timer"
    enabled: yes
    state: started
    daemon_reload: yes
  when:
    - restic_enable_prune | bool
    - restic_enable_timers | bool
    - (restic_backup_sources | selectattr('enabled') | list | length) > 0

- name: Enable and start check timer for first source
  ansible.builtin.systemd:
    name: "restic-check@{{ (restic_backup_sources | selectattr('enabled') | list | first).name }}.timer"
    enabled: yes
    state: started
    daemon_reload: yes
  when:
    - restic_enable_check | bool
    - restic_enable_timers | bool
    - (restic_backup_sources | selectattr('enabled') | list | length) > 0

- name: Enable and start scan timer for first source
  ansible.builtin.systemd:
    name: "restic-scan@{{ (restic_backup_sources | selectattr('enabled') | list | first).name }}.timer"
    enabled: yes
    state: started
    daemon_reload: yes
  when:
    - restic_enable_scan | bool
    - restic_enable_timers | bool
    - (restic_backup_sources | selectattr('enabled') | list | length) > 0

# ========================================
# SUMMARY
# ========================================

- name: Display deployment summary
  ansible.builtin.debug:
    msg:
      - "=== Restic Systemd Deployment Complete ==="
      - "Repository: {{ restic_repository }}"
      - "Backend: {{ restic_backend_type | upper }}"
      - "Backup sources: {{ restic_backup_sources | selectattr('enabled') | list | length }}"
      - "Enabled jobs: backup={{ restic_enable_backup }}, prune={{ restic_enable_prune }}, check={{ restic_enable_check }}, scan={{ restic_enable_scan }}"
      - "Timers enabled: {{ restic_enable_timers }}"
      - ""
      - "Check timer status with: systemctl list-timers 'restic-*'"
      - "View logs with: journalctl -u 'restic-*' -f"
