---
# roles/restic/defaults/main.yml
# Default variables for restic role
# All variables are prefixed with 'restic_' for namespace isolation

# ========================================
# ENCRYPTION KEYS (2-Key System)
# ========================================

# Generic key - used as fallback or for shared repositories
restic_generic_password: "{{ vault_restic_generic_password | default('') }}"

# Playbook-specific key - used for this specific playbook/environment
restic_playbook_password: "{{ vault_restic_playbook_password | default('') }}"

# Which password file to use (generic or playbook-specific)
restic_playbook_password_file: "playbook.key"
restic_generic_password_file: "generic.key"

# Use playbook-specific key by default
restic_use_playbook_key: true

# ========================================
# BACKEND CONFIGURATION
# ========================================

restic_backend_type: "s3"  # s3, local, sftp, rest

# S3 Backend (configure in group_vars or playbook)
restic_s3_bucket: ""  # Example: "my-backup-bucket"
restic_s3_region: ""  # Example: "eu-central-1"
restic_s3_access_key: "{{ vault_aws_access_key | default('') }}"
restic_s3_secret_key: "{{ vault_aws_secret_key | default('') }}"
restic_s3_endpoint: ""  # Empty for AWS, or custom endpoint (MinIO, Wasabi, etc.)
restic_s3_prefix: ""  # Optional path prefix in bucket, e.g. "restic"

# Local Backend (configure in group_vars or playbook)
restic_local_path: ""  # Example: "/mnt/backup/restic-repo"

# SFTP Backend (configure in group_vars or playbook)
restic_sftp_host: ""
restic_sftp_user: ""
restic_sftp_path: ""

# Repository URL (will be constructed automatically)
restic_repository: ""

# ========================================
# BACKUP SOURCES
# ========================================

# Define backup sources in group_vars or playbook
# Empty by default - role is generic and requires configuration
restic_backup_sources: []

# Example configuration:
# restic_backup_sources:
#   - name: "var-www"
#     path: "/var/www"
#     tags: ["web", "production"]
#     enabled: true
#     # Optional per-source settings:
#     # timeout_seconds: 7200  # Override default backup timeout
#     # retry_lock_duration: "5m"  # Override default retry-lock duration
#     # hook_pre_script: "{{ playbook_dir }}/hooks/pre-backup-var-www.sh"
#     # hook_post_script: "{{ playbook_dir }}/hooks/post-backup-var-www.sh"
#     # hook_script_dir: "/etc/restic/hooks"  # Override default hooks directory
#
#   - name: "etc"
#     path: "/etc"
#     tags: ["config", "system"]
#     enabled: true
#
#   - name: "home"
#     path: "/home"
#     tags: ["userdata"]
#     enabled: false

# ========================================
# EXCLUSIONS
# ========================================

restic_backup_excludes:
  - "*.tmp"
  - "*.cache"
  - "*.log"
  - "*/cache/*"
  - "*/tmp/*"
  - "*/node_modules/*"
  - "*/vendor/*"
  - "*/.git/*"
  - "*/lost+found/*"
  - "*.pyc"
  - "__pycache__"
  - "*.swp"
  - "*.swo"
  - "*~"

# ========================================
# BACKUP BEHAVIOR
# ========================================

# Force re-scan of all files (ignores change detection)
restic_force_rescan: false

# Optional: Force rescan on specific day of month (1-31, 0=disabled)
restic_force_rescan_day: 0

# ========================================
# SYSTEMD TIMER CONFIGURATION
# ========================================

# Backup timer settings
restic_timer_on_calendar: "daily"  # or use cron-like syntax: "Mon,Wed,Fri *-*-* 02:00:00"
restic_timer_on_boot_sec: "15min"
restic_timer_interval: "24h"
restic_timer_persistent: true
restic_timer_randomized_delay: "30min"
restic_timer_accuracy: "1h"

# Prune timer settings
restic_prune_timer_on_calendar: "weekly"
restic_prune_timer_on_boot_sec: "30min"
restic_prune_timer_interval: "7d"

# Check timer settings
restic_check_timer_on_calendar: "weekly"
restic_check_timer_on_boot_sec: "1h"
restic_check_timer_interval: "7d"
restic_check_read_data: false  # Set to true for full data integrity check (slower)
restic_check_read_data_subset: ""  # Example: "1/12" (check 1/12 of data), "10%" (10% random), "50M" (50 MiB)

# Scan timer settings
restic_scan_timer_on_calendar: "daily"
restic_scan_timer_on_boot_sec: "1h"
restic_scan_timer_interval: "1d"

# ========================================
# PERFORMANCE & LIMITS
# ========================================

# Read concurrency (parallel file reading)
restic_read_concurrency: 2

# Upload/Download limits in KiB/s (0 = unlimited)
restic_upload_limit_kbps: 0
restic_download_limit_kbps: 0

# CPU and I/O limits for systemd units
restic_cpu_quota: 80  # Percentage (100 = 1 core)
restic_io_weight: 100  # 1-10000, default 100
restic_nice_level: 10  # -20 to 19, higher = lower priority

# Backup timeout (0 = unlimited, systemd default)
restic_backup_timeout_seconds: 0  # Override per source with timeout_seconds

# Retry lock duration (wait if repository is locked)
restic_retry_lock_duration: "5m"  # Override per source with retry_lock_duration

# ========================================
# RETENTION POLICY
# ========================================

restic_retention_keep_last: 7
restic_retention_keep_hourly: 24
restic_retention_keep_daily: 14
restic_retention_keep_weekly: 8
restic_retention_keep_monthly: 12
restic_retention_keep_yearly: 5

# ========================================
# RESTIC LOCK MANAGEMENT
# ========================================

# NOTE: Restic uses native repository locks with a fixed 30-minute staleness threshold
# The 'restic unlock' command automatically removes locks older than 30 minutes
# This variable is kept for documentation purposes only
# Restic's --retry-lock flag (configured above) handles temporary locks automatically
restic_lock_max_age_hours: 12  # Informational only - Restic uses 30 minutes internally

# ========================================
# DIRECTORIES
# ========================================

# Configuration directory
restic_config_dir: "/etc/restic"

# Scripts directory
restic_scripts_dir: "/usr/local/bin/restic"

# Hooks directory (can be overridden per source)
restic_hooks_dir: "/etc/restic/hooks"

# ========================================
# HOOKS
# ========================================

# Custom hooks directory on control node
# Hooks must be created manually in this directory or on target hosts
# Example: restic_custom_hooks_dir: "{{ playbook_dir }}/hooks"
# Hook naming: pre-backup-<source-name>.sh, post-backup-<source-name>.sh
# Or use per-source hook_pre_script and hook_post_script variables
restic_custom_hooks_dir: ""

# ========================================
# MONITORING
# ========================================

# Syslog
restic_enable_syslog: true
restic_syslog_facility: "local0"
restic_syslog_tag: "restic"

# CheckMK monitoring
restic_enable_checkmk: true
restic_checkmk_spool_dir: "/var/lib/check_mk_agent/spool"
restic_checkmk_service_prefix: "Restic"

# ========================================
# SYSTEMD UNITS
# ========================================

# Enable/disable specific job types
restic_enable_backup: true
restic_enable_prune: true
restic_enable_check: true
restic_enable_scan: true

# Enable/disable timers (vs manual execution)
restic_enable_timers: true

# ========================================
# INSTALLATION
# ========================================

# Restic package name
restic_package_name: "restic"

# Additional packages
restic_additional_packages:
  - "jq"  # Required for JSON parsing in scripts
  - "bc"  # Required for calculations

# ========================================
# DEBUG MODE
# ========================================

# WARNING: ONLY enable for testing/debugging!
# When enabled, sensitive data (passwords, keys) may be visible in logs!
# NEVER use in production!
restic_debug_mode: false
