---
# roles/restic_backup/defaults/main.yml
# Default variables for restic_backup role
# Override these in your playbook or group_vars

# ========================================
# BACKUP TARGET SELECTION
# ========================================

backup_target_type: "s3"  # s3 or local

# ========================================
# S3 CONFIGURATION
# ========================================

s3_bucket: "my-backup-bucket"
s3_region: "eu-central-1"
s3_access_key: "{{ vault_aws_access_key | default('') }}"
s3_secret_key: "{{ vault_aws_secret_key | default('') }}"
s3_endpoint: ""  # Empty for AWS, or custom endpoint (MinIO, Wasabi, etc.)
s3_prefix: "restic"  # Optional path prefix in bucket

# ========================================
# LOCAL FOLDER CONFIGURATION
# ========================================

local_backup_path: "/mnt/backup/restic-repo"

# ========================================
# BACKUP STRATEGY
# ========================================

# Force re-scan of all files (ignores change detection)
backup_force_rescan: false

# Optional: Force rescan on specific day of month (1-31, 0=disabled)
backup_force_rescan_day: 0

# ========================================
# BACKUP INTERVALS
# ========================================

backup_interval_hours: 24

backup_time_window:
  enabled: false
  start_hour: 2
  end_hour: 5

# ========================================
# SOURCES & EXCLUSIONS
# ========================================

backup_sources:
  - path: "/var/www"
    tags: ["web", "production"]
    enabled: true
  - path: "/etc"
    tags: ["config", "system"]
    enabled: true

backup_excludes:
  - "*.tmp"
  - "*.cache"
  - "*.log"
  - "*/cache/*"
  - "*/tmp/*"
  - "*/node_modules/*"
  - "*/vendor/*"
  - "*/.git/*"
  - "*/lost+found/*"
  - "*.pyc"
  - "__pycache__"

# ========================================
# PERFORMANCE & LIMITS
# ========================================

# Read concurrency (parallel file reading)
restic_read_concurrency: 2

# Upload/Download limits in KiB/s (0 = unlimited)
restic_upload_limit_kbps: 0
restic_download_limit_kbps: 0

# ========================================
# RETENTION POLICIES
# ========================================

retention_policy:
  keep_last: 7
  keep_hourly: 24
  keep_daily: 14
  keep_weekly: 8
  keep_monthly: 12
  keep_yearly: 5

# ========================================
# SECURITY
# ========================================

# Restic repository password (from Ansible Vault)
restic_password: "{{ vault_restic_password | default('') }}"

# Configuration directory
restic_config_dir: "/root/.restic"

# ========================================
# PRE/POST BACKUP TASK FILES
# ========================================

# Path to external task file (optional)
pre_backup_tasks_file: ""
post_backup_tasks_file: ""

# ========================================
# LOGGING & NOTIFICATIONS
# ========================================

log_directory: "/var/log/restic"
log_retention_days: 30

# Syslog
enable_syslog: true
syslog_facility: "local0"
syslog_tag: "restic-backup"

# Check_MK monitoring
enable_checkmk: true
checkmk_spool_dir: "/var/lib/check_mk_agent/spool"
checkmk_service_name: "Restic_Backup"
checkmk_check_service_name: "Restic_Repository_Check"

# ========================================
# DEBUG MODE
# ========================================

# WARNING: ONLY enable for testing/debugging!
# When enabled, sensitive data (passwords, keys) will be visible in Ansible output!
# NEVER use in production or commit logs with debug_mode enabled!
debug_mode: false

# ========================================
# REPOSITORY CHECK
# ========================================

enable_repository_check: true
check_interval_days: 7